// <auto-generated />
using System;
using Dishora.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dishora.Migrations
{
    [DbContext(typeof(DishoraDbContext))]
    partial class DishoraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dishora.Models.business_details", b =>
                {
                    b.Property<long>("business_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("business_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("business_id"));

                    b.Property<string>("bir_reg_file")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("bir_reg_file");

                    b.Property<string>("bir_reg_no")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("bir_reg_no");

                    b.Property<string>("business_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("business_description");

                    b.Property<string>("business_duration")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("business_duration");

                    b.Property<string>("business_image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("business_image");

                    b.Property<string>("business_location")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("business_location");

                    b.Property<string>("business_name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("business_name");

                    b.Property<string>("business_permit_file")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("business_permit_file");

                    b.Property<string>("business_permit_no")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("business_permit_no");

                    b.Property<string>("business_type")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("business_type");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<double?>("latitude")
                        .HasColumnType("float")
                        .HasColumnName("latitude");

                    b.Property<double?>("longitude")
                        .HasColumnType("float")
                        .HasColumnName("longitude");

                    b.Property<string>("mayor_permit_file")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mayor_permit_file");

                    b.Property<int>("preorder_lead_time_hours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("preorder_lead_time_hours")
                        .HasDefaultValueSql("('48')");

                    b.Property<string>("remarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("remarks");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("valid_id_file")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("valid_id_file");

                    b.Property<string>("valid_id_no")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("valid_id_no");

                    b.Property<string>("valid_id_type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("valid_id_type");

                    b.Property<long>("vendor_id")
                        .HasColumnType("bigint")
                        .HasColumnName("vendor_id");

                    b.Property<string>("verification_status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("verification_status");

                    b.HasKey("business_id")
                        .HasName("PK__business__DC0DC16ED09F57DA");

                    b.HasIndex("vendor_id");

                    b.HasIndex(new[] { "business_name" }, "business_details_business_name_unique")
                        .IsUnique();

                    b.ToTable("business_details", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.business_opening_hours", b =>
                {
                    b.Property<long>("business_opening_hours_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("business_opening_hours_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("business_opening_hours_id"));

                    b.Property<long>("business_id")
                        .HasColumnType("bigint")
                        .HasColumnName("business_id");

                    b.Property<TimeOnly?>("closes_at")
                        .HasColumnType("time")
                        .HasColumnName("closes_at");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("day_of_week")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("day_of_week");

                    b.Property<bool>("is_closed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("is_closed")
                        .HasDefaultValueSql("('0')");

                    b.Property<TimeOnly?>("opens_at")
                        .HasColumnType("time")
                        .HasColumnName("opens_at");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("business_opening_hours_id")
                        .HasName("PK__business__07C3205740894924");

                    b.HasIndex("business_id");

                    b.ToTable("business_opening_hours", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.business_payment_methods", b =>
                {
                    b.Property<long>("business_payment_method_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("business_payment_method_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("business_payment_method_id"));

                    b.Property<long>("business_id")
                        .HasColumnType("bigint")
                        .HasColumnName("business_id");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<long>("payment_method_id")
                        .HasColumnType("bigint")
                        .HasColumnName("payment_method_id");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("business_payment_method_id")
                        .HasName("PK__business__609F6EF9D0092684");

                    b.HasIndex("payment_method_id");

                    b.HasIndex(new[] { "business_id", "payment_method_id" }, "business_payment_methods_business_id_payment_method_id_unique")
                        .IsUnique();

                    b.ToTable("business_payment_methods", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.business_pm_details", b =>
                {
                    b.Property<long>("business_pm_details_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("business_pm_details_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("business_pm_details_id"));

                    b.Property<string>("account_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("account_name");

                    b.Property<string>("account_number")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("account_number");

                    b.Property<long>("business_payment_method_id")
                        .HasColumnType("bigint")
                        .HasColumnName("business_payment_method_id");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("('1')");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("business_pm_details_id")
                        .HasName("PK__business__83D9FB0C2FB4D7A1");

                    b.HasIndex(new[] { "business_payment_method_id" }, "UQ_business_payment_method_id")
                        .IsUnique();

                    b.ToTable("business_pm_details", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.cache", b =>
                {
                    b.Property<string>("key")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("key");

                    b.Property<int>("expiration")
                        .HasColumnType("int")
                        .HasColumnName("expiration");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("key")
                        .HasName("cache_key_primary");

                    b.ToTable("cache", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.cache_locks", b =>
                {
                    b.Property<string>("key")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("key");

                    b.Property<int>("expiration")
                        .HasColumnType("int")
                        .HasColumnName("expiration");

                    b.Property<string>("owner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("owner");

                    b.HasKey("key")
                        .HasName("cache_locks_key_primary");

                    b.ToTable("cache_locks", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.checkout_drafts", b =>
                {
                    b.Property<long>("checkout_draft_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("checkout_draft_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("checkout_draft_id"));

                    b.Property<string>("cart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cart");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("delivery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("delivery");

                    b.Property<bool>("is_cod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("is_cod")
                        .HasDefaultValueSql("('0')");

                    b.Property<string>("item_notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("item_notes");

                    b.Property<long>("payment_method_id")
                        .HasColumnType("bigint")
                        .HasColumnName("payment_method_id");

                    b.Property<DateTime?>("processed_at")
                        .HasColumnType("datetime")
                        .HasColumnName("processed_at");

                    b.Property<decimal>("total")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("total");

                    b.Property<string>("transaction_id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("transaction_id");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("checkout_draft_id")
                        .HasName("PK__checkout__BEC51E282769ED44");

                    b.ToTable("checkout_drafts", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.customers", b =>
                {
                    b.Property<long>("customer_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("customer_id"));

                    b.Property<string>("contact_number")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("contact_number");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<double?>("latitude")
                        .HasColumnType("float")
                        .HasColumnName("latitude");

                    b.Property<double?>("longitude")
                        .HasColumnType("float")
                        .HasColumnName("longitude");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("user_address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_address");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("user_image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("user_image");

                    b.HasKey("customer_id")
                        .HasName("PK__customer__CD65CB85F8307575");

                    b.HasIndex("user_id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.delivery_addresses", b =>
                {
                    b.Property<long>("delivery_address_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("delivery_address_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("delivery_address_id"));

                    b.Property<string>("barangay")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("barangay");

                    b.Property<string>("city")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("city");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("full_address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_address");

                    b.Property<long>("order_id")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<string>("phone_number")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("postal_code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("postal_code");

                    b.Property<string>("province")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("province");

                    b.Property<string>("region")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("region");

                    b.Property<string>("street_name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("street_name");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("delivery_address_id")
                        .HasName("PK__delivery__B55B0D223CDBEAE2");

                    b.HasIndex("order_id");

                    b.HasIndex("user_id");

                    b.HasIndex(new[] { "city" }, "delivery_addresses_city_index");

                    b.HasIndex(new[] { "postal_code" }, "delivery_addresses_postal_code_index");

                    b.HasIndex(new[] { "province" }, "delivery_addresses_province_index");

                    b.ToTable("delivery_addresses", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.device_tokens", b =>
                {
                    b.Property<long>("device_token_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("device_token_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("device_token_id"));

                    b.Property<DateTime?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("last_seen")
                        .HasColumnType("datetime")
                        .HasColumnName("last_seen");

                    b.Property<string>("platform")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("platform");

                    b.Property<string>("provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("provider");

                    b.Property<string>("sns_endpoint_arn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sns_endpoint_arn");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("token");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("device_token_id")
                        .HasName("PK__device_t__3ADABB7DD781558C");

                    b.HasIndex(new[] { "user_id", "is_active" }, "IX_device_tokens_user_active");

                    b.ToTable("device_tokens", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.dietary_specifications", b =>
                {
                    b.Property<long>("dietary_specification_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("dietary_specification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("dietary_specification_id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("dietary_spec_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("dietary_spec_name");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("dietary_specification_id")
                        .HasName("PK__dietary___7B2CC1C5F5F03468");

                    b.ToTable("dietary_specifications", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.failed_jobs", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("connection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("connection");

                    b.Property<string>("exception")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("exception");

                    b.Property<DateTime>("failed_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("failed_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload");

                    b.Property<string>("queue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("queue");

                    b.Property<string>("uu_id")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("uuid");

                    b.HasKey("id")
                        .HasName("PK__failed_j__3213E83F8AAC85BF");

                    b.HasIndex(new[] { "uu_id" }, "failed_jobs_uuid_unique")
                        .IsUnique();

                    b.ToTable("failed_jobs", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.job_batches", b =>
                {
                    b.Property<string>("id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id");

                    b.Property<int?>("cancelled_at")
                        .HasColumnType("int")
                        .HasColumnName("cancelled_at");

                    b.Property<int>("created_at")
                        .HasColumnType("int")
                        .HasColumnName("created_at");

                    b.Property<string>("failed_job_ids")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("failed_job_ids");

                    b.Property<int>("failed_jobs")
                        .HasColumnType("int")
                        .HasColumnName("failed_jobs");

                    b.Property<int?>("finished_at")
                        .HasColumnType("int")
                        .HasColumnName("finished_at");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("options")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("options");

                    b.Property<int>("pending_jobs")
                        .HasColumnType("int")
                        .HasColumnName("pending_jobs");

                    b.Property<int>("total_jobs")
                        .HasColumnType("int")
                        .HasColumnName("total_jobs");

                    b.HasKey("id")
                        .HasName("job_batches_id_primary");

                    b.ToTable("job_batches", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.jobs", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<byte>("attempts")
                        .HasColumnType("tinyint")
                        .HasColumnName("attempts");

                    b.Property<int>("available_at")
                        .HasColumnType("int")
                        .HasColumnName("available_at");

                    b.Property<int>("created_at")
                        .HasColumnType("int")
                        .HasColumnName("created_at");

                    b.Property<string>("payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload");

                    b.Property<string>("queue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("queue");

                    b.Property<int?>("reserved_at")
                        .HasColumnType("int")
                        .HasColumnName("reserved_at");

                    b.HasKey("id")
                        .HasName("PK__jobs__3213E83FDC0633ED");

                    b.HasIndex(new[] { "queue" }, "jobs_queue_index");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.messages", b =>
                {
                    b.Property<long>("message_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("message_id"));

                    b.Property<bool>("is_read")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("is_read")
                        .HasDefaultValueSql("('0')");

                    b.Property<string>("message_text")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message_text");

                    b.Property<long>("receiver_id")
                        .HasColumnType("bigint")
                        .HasColumnName("receiver_id");

                    b.Property<string>("receiver_role")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("receiver_role");

                    b.Property<long>("sender_id")
                        .HasColumnType("bigint")
                        .HasColumnName("sender_id");

                    b.Property<string>("sender_role")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sender_role");

                    b.Property<DateTime>("sent_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("message_id")
                        .HasName("PK__messages__0BBF6EE6A246B939");

                    b.HasIndex(new[] { "receiver_id", "receiver_role" }, "messages_receiver_id_receiver_role_index");

                    b.HasIndex(new[] { "sender_id", "sender_role" }, "messages_sender_id_sender_role_index");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.migration", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("batch")
                        .HasColumnType("int")
                        .HasColumnName("batch");

                    b.Property<string>("migration1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("migration");

                    b.HasKey("id")
                        .HasName("PK__migratio__3213E83F940046B0");

                    b.ToTable("migrations", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.notification_deliveries", b =>
                {
                    b.Property<long>("delivery_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("delivery_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("delivery_id"));

                    b.Property<DateTime?>("attempted_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("attempted_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("notification_id")
                        .HasColumnType("bigint")
                        .HasColumnName("notification_id");

                    b.Property<string>("provider")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("provider");

                    b.Property<string>("provider_response")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("provider_response");

                    b.Property<bool?>("success")
                        .HasColumnType("bit")
                        .HasColumnName("success");

                    b.HasKey("delivery_id")
                        .HasName("PK__notifica__1C5CF4F525371EB5");

                    b.HasIndex("notification_id");

                    b.ToTable("notification_deliveries", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.notification_preferences", b =>
                {
                    b.Property<long>("preference_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("preference_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("preference_id"));

                    b.Property<string>("channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("channel");

                    b.Property<bool>("enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<string>("event_type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTime?>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("preference_id")
                        .HasName("PK__notifica__FB41DBCF922A6C67");

                    b.HasIndex(new[] { "user_id", "event_type", "channel" }, "UC_notification_pref")
                        .IsUnique();

                    b.ToTable("notification_preferences", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.notifications", b =>
                {
                    b.Property<long>("notification_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("notification_id"));

                    b.Property<long?>("actor_user_id")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_user_id");

                    b.Property<long?>("business_id")
                        .HasColumnType("bigint")
                        .HasColumnName("business_id");

                    b.Property<string>("channel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("in_app")
                        .HasColumnName("channel");

                    b.Property<DateTime?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("event_type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTime?>("expires_at")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<bool>("is_global")
                        .HasColumnType("bit")
                        .HasColumnName("is_global");

                    b.Property<bool>("is_read")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("payload")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload");

                    b.Property<string>("recipient_role")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("recipient_role");

                    b.Property<long?>("reference_id")
                        .HasColumnType("bigint")
                        .HasColumnName("reference_id");

                    b.Property<string>("reference_table")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("reference_table");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("notification_id")
                        .HasName("PK__notifica__E059842F31B9C5FC");

                    b.HasIndex(new[] { "user_id", "is_read", "created_at" }, "IX_notifications_user_read_created");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.order_items", b =>
                {
                    b.Property<long>("order_item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("order_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("order_item_id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("is_pre_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("is_pre_order")
                        .HasDefaultValueSql("('0')");

                    b.Property<long>("order_id")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<string>("order_item_note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("order_item_note");

                    b.Property<string>("order_item_status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("order_item_status");

                    b.Property<decimal>("price_at_order_time")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price_at_order_time");

                    b.Property<string>("product_description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("product_description");

                    b.Property<long>("product_id")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<string>("product_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("product_name");

                    b.Property<int>("quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("order_item_id")
                        .HasName("PK__order_it__3764B6BCCCB802C6");

                    b.HasIndex("order_id");

                    b.HasIndex("product_id");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.order_sessions", b =>
                {
                    b.Property<long>("order_session_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("order_session_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("order_session_id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("orders")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("orders");

                    b.Property<string>("session_id")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("session_id");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<long?>("user_id")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("order_session_id")
                        .HasName("PK__order_se__48134B5EC839221C");

                    b.ToTable("order_sessions", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.orders", b =>
                {
                    b.Property<long>("order_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("order_id"));

                    b.Property<long>("business_id")
                        .HasColumnType("bigint")
                        .HasColumnName("business_id");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("delivery_date")
                        .HasColumnType("date")
                        .HasColumnName("delivery_date");

                    b.Property<string>("delivery_time")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("delivery_time");

                    b.Property<long>("payment_method_id")
                        .HasColumnType("bigint")
                        .HasColumnName("payment_method_id");

                    b.Property<decimal>("total")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("total");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("order_id")
                        .HasName("PK__orders__46596229259F2E55");

                    b.HasIndex("business_id");

                    b.HasIndex("payment_method_id");

                    b.HasIndex("user_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.password_reset_tokens", b =>
                {
                    b.Property<string>("email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("token");

                    b.HasKey("email")
                        .HasName("password_reset_tokens_email_primary");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.payment_details", b =>
                {
                    b.Property<long>("payment_detail_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("payment_detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("payment_detail_id"));

                    b.Property<decimal?>("amount_paid")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("amount_paid");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<long>("order_id")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("paid_at")
                        .HasColumnType("datetime")
                        .HasColumnName("paid_at");

                    b.Property<long>("payment_method_id")
                        .HasColumnType("bigint")
                        .HasColumnName("payment_method_id");

                    b.Property<string>("payment_reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("payment_reference");

                    b.Property<string>("payment_status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("payment_status");

                    b.Property<string>("transaction_id")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("transaction_id");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("payment_detail_id")
                        .HasName("PK__payment___C66E6E368AD9887A");

                    b.HasIndex("order_id");

                    b.HasIndex("payment_method_id");

                    b.ToTable("payment_details", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.payment_methods", b =>
                {
                    b.Property<long>("payment_method_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("payment_method_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("payment_method_id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("method_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("method_name");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("payment_method_id")
                        .HasName("PK__payment___8A3EA9EB4A7D74F4");

                    b.ToTable("payment_methods", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.pre_orders", b =>
                {
                    b.Property<long>("pre_order_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pre_order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("pre_order_id"));

                    b.Property<decimal>("advance_paid_amount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("advance_paid_amount");

                    b.Property<decimal>("amount_due")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("amount_due");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<long>("order_id")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<string>("payment_option")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("payment_option");

                    b.Property<string>("payment_transaction_id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("payment_transaction_id");

                    b.Property<string>("preorder_status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("pending_payment")
                        .HasColumnName("preorder_status");

                    b.Property<string>("receipt_url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("receipt_url");

                    b.Property<decimal>("total_advance_required")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("total_advance_required");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("pre_order_id")
                        .HasName("PK__pre_orde__FC60B68D38DC36D5");

                    b.HasIndex(new[] { "order_id" }, "UQ_pre_orders_order_id")
                        .IsUnique();

                    b.ToTable("pre_orders", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.preorder_schedule", b =>
                {
                    b.Property<long>("schedule_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("schedule_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("schedule_id"));

                    b.Property<DateOnly>("available_date")
                        .HasColumnType("date")
                        .HasColumnName("available_date");

                    b.Property<long>("business_id")
                        .HasColumnType("bigint")
                        .HasColumnName("business_id");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("current_order_count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("current_order_count")
                        .HasDefaultValueSql("('0')");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("('1')");

                    b.Property<int>("max_orders")
                        .HasColumnType("int")
                        .HasColumnName("max_orders");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("schedule_id")
                        .HasName("PK__preorder__C46A8A6FD8342062");

                    b.HasIndex(new[] { "business_id", "available_date" }, "preorder_schedule_business_id_available_date_unique")
                        .IsUnique();

                    b.ToTable("preorder_schedule", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.product_categories", b =>
                {
                    b.Property<long>("product_category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("product_category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("product_category_id"));

                    b.Property<string>("category_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category_name");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("product_category_id")
                        .HasName("PK__product___1F8847F92E946C37");

                    b.ToTable("product_categories", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.product_dietary_specifications", b =>
                {
                    b.Property<long>("product_id")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<long>("dietary_specification_id")
                        .HasColumnType("bigint")
                        .HasColumnName("dietary_specification_id");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("product_id", "dietary_specification_id")
                        .HasName("product_dietary_specifications_product_id_dietary_specification_id_primary");

                    b.HasIndex("dietary_specification_id");

                    b.ToTable("product_dietary_specifications", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.products", b =>
                {
                    b.Property<long>("product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("product_id"));

                    b.Property<decimal>("advance_amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("advance_amount")
                        .HasDefaultValueSql("('0')");

                    b.Property<long>("business_id")
                        .HasColumnType("bigint")
                        .HasColumnName("business_id");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int?>("cutoff_minutes")
                        .HasColumnType("int")
                        .HasColumnName("cutoff_minutes");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("image_url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("image_url");

                    b.Property<bool>("is_available")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("is_available")
                        .HasDefaultValueSql("('1')");

                    b.Property<bool>("is_pre_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("is_pre_order")
                        .HasDefaultValueSql("('0')");

                    b.Property<string>("item_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("item_name");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.Property<long?>("product_category_id")
                        .HasColumnType("bigint")
                        .HasColumnName("product_category_id");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("product_id")
                        .HasName("PK__products__47027DF5730B421E");

                    b.HasIndex("business_id");

                    b.HasIndex("product_category_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.reviews", b =>
                {
                    b.Property<long>("review_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("review_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("review_id"));

                    b.Property<long>("business_id")
                        .HasColumnType("bigint")
                        .HasColumnName("business_id");

                    b.Property<string>("comment")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<long>("customer_id")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<int>("rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("review_id")
                        .HasName("PK__reviews__60883D90D2154919");

                    b.HasIndex("business_id");

                    b.HasIndex("customer_id");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.sessions", b =>
                {
                    b.Property<string>("id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("ip_address")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<int>("last_activity")
                        .HasColumnType("int")
                        .HasColumnName("last_activity");

                    b.Property<string>("payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload");

                    b.Property<string>("user_agent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_agent");

                    b.Property<long?>("user_id")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("id")
                        .HasName("sessions_id_primary");

                    b.HasIndex(new[] { "last_activity" }, "sessions_last_activity_index");

                    b.HasIndex(new[] { "user_id" }, "sessions_user_id_index");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.users", b =>
                {
                    b.Property<long>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("user_id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("email_verified_at")
                        .HasColumnType("datetime")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("fullname")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("fullname");

                    b.Property<bool>("is_verified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("is_verified")
                        .HasDefaultValueSql("('0')");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("remember_token")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("remember_token");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("username");

                    b.Property<string>("verification_token")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("verification_token");

                    b.HasKey("user_id")
                        .HasName("PK__users__B9BE370F29D3F97B");

                    b.HasIndex(new[] { "email" }, "users_email_unique")
                        .IsUnique();

                    b.HasIndex(new[] { "username" }, "users_username_unique")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.valid_ids", b =>
                {
                    b.Property<long>("valid_id_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("valid_id_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("valid_id_id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("valid_id_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("valid_id_name");

                    b.HasKey("valid_id_id")
                        .HasName("PK__valid_id__FCBC6B5B1980E305");

                    b.ToTable("valid_ids", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.vendors", b =>
                {
                    b.Property<long>("vendor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("vendor_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("vendor_id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("fullname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("fullname");

                    b.Property<string>("phone_number")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("registration_status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("registration_status");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("vendor_id")
                        .HasName("PK__vendors__0F7D2B789F3A74BA");

                    b.HasIndex(new[] { "user_id" }, "vendors_user_id_unique")
                        .IsUnique();

                    b.ToTable("vendors", (string)null);
                });

            modelBuilder.Entity("Dishora.Models.business_details", b =>
                {
                    b.HasOne("Dishora.Models.vendors", "vendor")
                        .WithMany("BusinessDetails")
                        .HasForeignKey("vendor_id")
                        .IsRequired()
                        .HasConstraintName("business_details_vendor_id_foreign");

                    b.Navigation("vendor");
                });

            modelBuilder.Entity("Dishora.Models.business_opening_hours", b =>
                {
                    b.HasOne("Dishora.Models.business_details", "business")
                        .WithMany("opening_hours")
                        .HasForeignKey("business_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("business_opening_hours_business_id_foreign");

                    b.Navigation("business");
                });

            modelBuilder.Entity("Dishora.Models.business_payment_methods", b =>
                {
                    b.HasOne("Dishora.Models.business_details", "business")
                        .WithMany("payment_methods")
                        .HasForeignKey("business_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("business_payment_methods_business_id_foreign");

                    b.HasOne("Dishora.Models.payment_methods", "payment_method")
                        .WithMany("BusinessPaymentMethods")
                        .HasForeignKey("payment_method_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("business_payment_methods_payment_method_id_foreign");

                    b.Navigation("business");

                    b.Navigation("payment_method");
                });

            modelBuilder.Entity("Dishora.Models.business_pm_details", b =>
                {
                    b.HasOne("Dishora.Models.business_payment_methods", "business_payment_method")
                        .WithOne("business_pm_detail")
                        .HasForeignKey("Dishora.Models.business_pm_details", "business_payment_method_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("business_pm_details_business_payment_method_id_foreign");

                    b.Navigation("business_payment_method");
                });

            modelBuilder.Entity("Dishora.Models.customers", b =>
                {
                    b.HasOne("Dishora.Models.users", "user")
                        .WithMany("customers")
                        .HasForeignKey("user_id")
                        .IsRequired()
                        .HasConstraintName("customers_user_id_foreign");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Dishora.Models.delivery_addresses", b =>
                {
                    b.HasOne("Dishora.Models.orders", "Order")
                        .WithMany("delivery_address")
                        .HasForeignKey("order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("delivery_addresses_order_id_foreign");

                    b.HasOne("Dishora.Models.users", "User")
                        .WithMany("deliveryaddresses")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("delivery_addresses_user_id_foreign");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dishora.Models.device_tokens", b =>
                {
                    b.HasOne("Dishora.Models.users", "User")
                        .WithMany("devicetokens")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_device_tokens_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dishora.Models.notification_deliveries", b =>
                {
                    b.HasOne("Dishora.Models.notifications", "notification")
                        .WithMany("notificationdeliveries")
                        .HasForeignKey("notification_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_notification_deliveries_notification");

                    b.Navigation("notification");
                });

            modelBuilder.Entity("Dishora.Models.notification_preferences", b =>
                {
                    b.HasOne("Dishora.Models.users", "User")
                        .WithMany("notificationpreferences")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_notification_preferences_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dishora.Models.notifications", b =>
                {
                    b.HasOne("Dishora.Models.users", "User")
                        .WithMany("notifications")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_notifications_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dishora.Models.order_items", b =>
                {
                    b.HasOne("Dishora.Models.orders", "order")
                        .WithMany("order_item")
                        .HasForeignKey("order_id")
                        .IsRequired()
                        .HasConstraintName("order_items_order_id_foreign");

                    b.HasOne("Dishora.Models.products", "product")
                        .WithMany("order_items")
                        .HasForeignKey("product_id")
                        .IsRequired()
                        .HasConstraintName("order_items_product_id_foreign");

                    b.Navigation("order");

                    b.Navigation("product");
                });

            modelBuilder.Entity("Dishora.Models.orders", b =>
                {
                    b.HasOne("Dishora.Models.business_details", "business")
                        .WithMany("orders")
                        .HasForeignKey("business_id")
                        .IsRequired()
                        .HasConstraintName("orders_business_id_foreign");

                    b.HasOne("Dishora.Models.payment_methods", "payment_method")
                        .WithMany("orders")
                        .HasForeignKey("payment_method_id")
                        .IsRequired()
                        .HasConstraintName("orders_payment_method_id_foreign");

                    b.HasOne("Dishora.Models.users", "User")
                        .WithMany("orders")
                        .HasForeignKey("user_id")
                        .IsRequired()
                        .HasConstraintName("orders_user_id_foreign");

                    b.Navigation("User");

                    b.Navigation("business");

                    b.Navigation("payment_method");
                });

            modelBuilder.Entity("Dishora.Models.payment_details", b =>
                {
                    b.HasOne("Dishora.Models.orders", "order")
                        .WithMany("payment_detail")
                        .HasForeignKey("order_id")
                        .IsRequired()
                        .HasConstraintName("payment_details_order_id_foreign");

                    b.HasOne("Dishora.Models.payment_methods", "payment_method")
                        .WithMany("payment_details")
                        .HasForeignKey("payment_method_id")
                        .IsRequired()
                        .HasConstraintName("payment_details_payment_method_id_foreign");

                    b.Navigation("order");

                    b.Navigation("payment_method");
                });

            modelBuilder.Entity("Dishora.Models.pre_orders", b =>
                {
                    b.HasOne("Dishora.Models.orders", "Order")
                        .WithOne("preorder")
                        .HasForeignKey("Dishora.Models.pre_orders", "order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("pre_orders_order_id_foreign");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Dishora.Models.preorder_schedule", b =>
                {
                    b.HasOne("Dishora.Models.business_details", "business")
                        .WithMany("preorder_schedule")
                        .HasForeignKey("business_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("preorder_schedule_business_id_foreign");

                    b.Navigation("business");
                });

            modelBuilder.Entity("Dishora.Models.product_dietary_specifications", b =>
                {
                    b.HasOne("Dishora.Models.dietary_specifications", "dietary_specification")
                        .WithMany("product_dietary_specifications")
                        .HasForeignKey("dietary_specification_id")
                        .IsRequired()
                        .HasConstraintName("product_dietary_specifications_dietary_specification_id_foreign");

                    b.HasOne("Dishora.Models.products", "product")
                        .WithMany("product_dietary_specifications")
                        .HasForeignKey("product_id")
                        .IsRequired()
                        .HasConstraintName("product_dietary_specifications_product_id_foreign");

                    b.Navigation("dietary_specification");

                    b.Navigation("product");
                });

            modelBuilder.Entity("Dishora.Models.products", b =>
                {
                    b.HasOne("Dishora.Models.business_details", "business")
                        .WithMany("products")
                        .HasForeignKey("business_id")
                        .IsRequired()
                        .HasConstraintName("products_business_id_foreign");

                    b.HasOne("Dishora.Models.product_categories", "product_category")
                        .WithMany("products")
                        .HasForeignKey("product_category_id")
                        .HasConstraintName("products_product_category_id_foreign");

                    b.Navigation("business");

                    b.Navigation("product_category");
                });

            modelBuilder.Entity("Dishora.Models.reviews", b =>
                {
                    b.HasOne("Dishora.Models.business_details", "business")
                        .WithMany("reviews")
                        .HasForeignKey("business_id")
                        .IsRequired()
                        .HasConstraintName("reviews_business_id_foreign");

                    b.HasOne("Dishora.Models.customers", "customer")
                        .WithMany("reviews")
                        .HasForeignKey("customer_id")
                        .IsRequired()
                        .HasConstraintName("reviews_customer_id_foreign");

                    b.Navigation("business");

                    b.Navigation("customer");
                });

            modelBuilder.Entity("Dishora.Models.vendors", b =>
                {
                    b.HasOne("Dishora.Models.users", "User")
                        .WithOne("vendor")
                        .HasForeignKey("Dishora.Models.vendors", "user_id")
                        .IsRequired()
                        .HasConstraintName("vendors_user_id_foreign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dishora.Models.business_details", b =>
                {
                    b.Navigation("opening_hours");

                    b.Navigation("orders");

                    b.Navigation("payment_methods");

                    b.Navigation("preorder_schedule");

                    b.Navigation("products");

                    b.Navigation("reviews");
                });

            modelBuilder.Entity("Dishora.Models.business_payment_methods", b =>
                {
                    b.Navigation("business_pm_detail")
                        .IsRequired();
                });

            modelBuilder.Entity("Dishora.Models.customers", b =>
                {
                    b.Navigation("reviews");
                });

            modelBuilder.Entity("Dishora.Models.dietary_specifications", b =>
                {
                    b.Navigation("product_dietary_specifications");
                });

            modelBuilder.Entity("Dishora.Models.notifications", b =>
                {
                    b.Navigation("notificationdeliveries");
                });

            modelBuilder.Entity("Dishora.Models.orders", b =>
                {
                    b.Navigation("delivery_address");

                    b.Navigation("order_item");

                    b.Navigation("payment_detail");

                    b.Navigation("preorder");
                });

            modelBuilder.Entity("Dishora.Models.payment_methods", b =>
                {
                    b.Navigation("BusinessPaymentMethods");

                    b.Navigation("orders");

                    b.Navigation("payment_details");
                });

            modelBuilder.Entity("Dishora.Models.product_categories", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("Dishora.Models.products", b =>
                {
                    b.Navigation("order_items");

                    b.Navigation("product_dietary_specifications");
                });

            modelBuilder.Entity("Dishora.Models.users", b =>
                {
                    b.Navigation("customers");

                    b.Navigation("deliveryaddresses");

                    b.Navigation("devicetokens");

                    b.Navigation("notificationpreferences");

                    b.Navigation("notifications");

                    b.Navigation("orders");

                    b.Navigation("vendor");
                });

            modelBuilder.Entity("Dishora.Models.vendors", b =>
                {
                    b.Navigation("BusinessDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
